### ISSUE TITLE
Typo to be corrected 

### ISSUE THREAD

**Issue by rParslow** [TurtleForGaming/LinkyLink#1]
Hi Samuel 

Could you correct the "Non transmit" in "Non transmis" 
It would be better :) 

Is there an easy way to add english language ? 
But not sure it's important Linky is only in France 

Merci

**Comment by TheStaticTurtle** [comment]
Thanks, I completely forgot to correct my typos.
Adding the English might be complicated since I don't store any settings, but in the future, I might do it.
